spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HotelManagement?createDatabaseIfNotExist=true
    username: root
    password: Pavan@2010
  jpa:
    hibernate:
      ddl_auto: create
    show_sql: true

server:
  port: 8999