spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ProjectJuly
    username: root
    password: Pavan@2010

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

server:
  port: 8000