spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_kal
    username: root
    password: Pavan@2010

  jpa:
    show_sql: true
    hibernate:
      ddl_auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect